CREATE TABLE Reconhecimento (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  deviceKey VARCHAR(255) NOT NULL,
  personId VARCHAR(255) NOT NULL,
  dataDeCriacao TIMESTAMP NOT NULL,
  time VARCHAR(255) NOT NULL,
  ip VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  path VARCHAR(255) NOT NULL
);